site_name: 근거 기반 한의학 위키
site_description: Evidence-Based Korean Medicine Wiki
site_url: https://wiki.symbolicinfo.com
docs_dir: wiki
theme:
  name: material
hooks:
  - hooks/canonical.py
markdown_extensions:
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search
  - awesome-pages
  - htmlproofer:
      enabled: !ENV [CI, false]
  - redirects:
      redirect_maps: {}
  - macros
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      type: date
      locale: ko
      fallback_to_build_date: true
  - glightbox
  - open-in-new-tab
  - pdf-export:
      enabled_if_env: ENABLE_PDF_EXPORT
  - print-site
extra_javascript:
  - assets/gtag.js

